### ISSUE TITLE
SDK requires field HtEnabled to be set on MachineCfg. Firecracker >0.25.0 does not support this parameter

### ISSUE THREAD

**Issue by dps** [firecracker-microvm/firecracker-go-sdk#381]
Firecracker returns this error when HtEnabled is set on the MachineCfg via the Go SDK

```
2022-02-08T03:10:07.029623118 [anonymous-instance:fc_api:ERROR:src/api_server/src/lib.rs:270] An error occurred when deserializing the json body of a request: unknown field `ht_enabled`, expected one of `vcpu_count`, `mem_size_mib`, `smt`, `cpu_template`, `track_dirty_pages` at line 1 column 13.
```

However, not setting `HtEnabled` at all fails to validate on the client (SDK) side:
```
Failed handler "validate.Cfg": machine needs a setting for ht_enabled 
2022/02/08 03:08:47 Failed to start machine: machine needs a setting for ht_enabled
```

It appears ht_enabled was renamed to smt after version 0.25.0 and the SDK needs to be updated to account for that:
Here's a relevant part of the test code:
https://github.com/firecracker-microvm/firecracker/blob/main/tests/framework/resources.py#L628

**Comment by dps** [comment]
More broadly, the SDK needs to be updated for firecracker 1.0 - I forked to fix the above issue and then ran into:
```
2022/02/08 04:15:54 Failed to start machine: [PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:An error occurred when deserializing the json body of a request: unknown field `allow_mmds_requests`, expected one of `iface_id`, `host_dev_name`, `guest_mac`, `rx_rate_limiter`, `tx_rate_limiter` at line 1 column 22.}
```

The v1.0 changelog says:
> Remove allow_mmds_requests field from the request body that attaches network interfaces. Specifying interfaces that allow forwarding requests to MMDS is done by adding the network interface's ID to the network_interfaces field of PUT /mmds/config request's body.

**Comment by kzys** [comment]
Yes. There are a few breaking changes on Firecracker side, since it is their first 1.0 release. We will update the SDK shortly to at least make existing features work.

**Comment by Kern--** [comment]
This should be resolved with #382

**Comment by alexellis** [comment]
I also ran into this, then tried to remove the field to get the VM to create, and it still failed with firecracker 1.0:

```
WARN[0001] Failed handler "validate.Cfg": machine needs a setting for ht_enabled 
failed to start the vm: machine needs a setting for ht_enabled
```

@Kern-- please can you create a new release in this repository, so that Go.mod can be updated to a release instead of a SHA? The last release was 23 Oct 2020 and your commit was 15 days ago.

I noticed a similar issue with other firecracker repositories, is there a reason why releases are not being made?
